// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using NoCoFoodTrucks.Models;
using System;

namespace NoCoFoodTrucks.Migrations
{
    [DbContext(typeof(NoCoFoodTrucksContext))]
    [Migration("20180321034424_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NoCoFoodTrucks.Models.Truck", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Facebook");

                    b.Property<string>("Name");

                    b.Property<string>("Twitter");

                    b.Property<string>("Website");

                    b.Property<string>("Yelp");

                    b.HasKey("ID");

                    b.ToTable("Truck");
                });
#pragma warning restore 612, 618
        }
    }
}
